-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cliente"
(
    id_cliente integer NOT NULL,
    persona integer,
    CONSTRAINT "Cliente_pkey" PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public."Componente"
(
    id_componente integer NOT NULL,
    descuento integer,
    tipo character varying COLLATE pg_catalog."default",
    marca character varying COLLATE pg_catalog."default",
    precio integer,
    CONSTRAINT "Componente_pkey" PRIMARY KEY (id_componente)
);

CREATE TABLE IF NOT EXISTS public."Descuento"
(
    id_descuento integer NOT NULL,
    descuento_porcentual integer,
    detalle_descuento character varying COLLATE pg_catalog."default",
    CONSTRAINT "Descuento_pkey" PRIMARY KEY (id_descuento)
);

CREATE TABLE IF NOT EXISTS public."Factura"
(
    id_factura integer NOT NULL,
    metodo_pago character varying COLLATE pg_catalog."default",
    fecha integer,
    precio_total integer,
    CONSTRAINT "Factura_pkey" PRIMARY KEY (id_factura)
);

CREATE TABLE IF NOT EXISTS public."FechaLimite"
(
    id_fecha integer NOT NULL,
    "fecha-solicitud-facturacion" date,
    "fecha-limite" date,
    CONSTRAINT "FechaLimite_pkey" PRIMARY KEY (id_fecha)
);

CREATE TABLE IF NOT EXISTS public."Garantia"
(
    id_garantia integer NOT NULL,
    detalle_garantia character varying COLLATE pg_catalog."default",
    "años" integer,
    CONSTRAINT "Garantia_pkey" PRIMARY KEY (id_garantia)
);

CREATE TABLE IF NOT EXISTS public."Pedido"
(
    id_pedido integer NOT NULL,
    garantia integer,
    cliente integer,
    factura integer,
    descuento integer,
    fecha integer,
    CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public."PedidoComponente"
(
    componente integer NOT NULL,
    pedido integer NOT NULL,
    cantidad integer,
    CONSTRAINT pket PRIMARY KEY (pedido, componente)
);

CREATE TABLE IF NOT EXISTS public."Persona"
(
    "RUN" character varying COLLATE pg_catalog."default" NOT NULL,
    "PrimerNombre" character varying COLLATE pg_catalog."default",
    "Apellido1" character varying COLLATE pg_catalog."default",
    "Apellido2" character varying COLLATE pg_catalog."default",
    "Direccion" character varying COLLATE pg_catalog."default",
    "Telefono" bigint,
    id_persona integer NOT NULL,
    CONSTRAINT "id-persona-pkey" PRIMARY KEY (id_persona)
);

CREATE TABLE IF NOT EXISTS public."Tecnico"
(
    id_tecnico integer NOT NULL,
    persona integer,
    CONSTRAINT tecnico_pkey PRIMARY KEY (id_tecnico)
);

CREATE TABLE IF NOT EXISTS public."TecnicoPedido"
(
    tecnico integer NOT NULL,
    pedido integer NOT NULL,
    CONSTRAINT "TecnicoPedido_pkey" PRIMARY KEY (tecnico, pedido)
);

ALTER TABLE IF EXISTS public."Cliente"
    ADD CONSTRAINT "persona-fkey" FOREIGN KEY (persona)
    REFERENCES public."Persona" (id_persona) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Componente"
    ADD CONSTRAINT descuento FOREIGN KEY (descuento)
    REFERENCES public."Descuento" (id_descuento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Factura"
    ADD CONSTRAINT factura FOREIGN KEY (fecha)
    REFERENCES public."FechaLimite" (id_fecha) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "cliente-fkey" FOREIGN KEY (cliente)
    REFERENCES public."Cliente" (id_cliente) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "descuento-fkey" FOREIGN KEY (descuento)
    REFERENCES public."Descuento" (id_descuento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "factura-fkey" FOREIGN KEY (factura)
    REFERENCES public."Factura" (id_factura) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "fecha-fkey" FOREIGN KEY (fecha)
    REFERENCES public."FechaLimite" (id_fecha) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "garantia-fkey" FOREIGN KEY (garantia)
    REFERENCES public."Garantia" (id_garantia) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."PedidoComponente"
    ADD CONSTRAINT "componente-fkey" FOREIGN KEY (componente)
    REFERENCES public."Componente" (id_componente) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PedidoComponente"
    ADD CONSTRAINT "pedido-fkey" FOREIGN KEY (pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tecnico"
    ADD CONSTRAINT "persona-tecnico-fkey" FOREIGN KEY (persona)
    REFERENCES public."Persona" (id_persona) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."TecnicoPedido"
    ADD CONSTRAINT "pedido-fkey" FOREIGN KEY (pedido)
    REFERENCES public."Pedido" (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."TecnicoPedido"
    ADD CONSTRAINT "tecnico-fkey" FOREIGN KEY (tecnico)
    REFERENCES public."Tecnico" (id_tecnico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;