INSERT INTO public."Garantia"(
	id_garantia, detalle_garantia, "años")
VALUES
(1, 'Garantía de pintura contra rayaduras', 1),
(2, 'Garantía extendida para suspensión', 1),
(3, 'Garantía limitada para accesorios adicionales', 1),
(4, 'Garantía contra corrosión en bicicletas de aluminio', 1),
(5, 'Garantía extendida para frenos', 3),
(6, 'Garantía limitada para ruedas', 2),
(7, 'Garantía estándar para cuadro de bicicleta', 2),
(8, 'Garantía para defectos de fábrica', 3),
(9, 'Garantía completa en bicicletas eléctricas', 3),
(10, 'Garantía completa en bicicletas eléctricas', 3),
(11, 'Garantía extendida para frenos', 3),
(12, 'Garantía contra corrosión en bicicletas de aluminio', 2),
(13, 'Garantía de pintura contra rayaduras', 3),
(14, 'Garantía completa en bicicletas eléctricas', 2),
(15, 'Garantía completa en bicicletas eléctricas', 2),
(16, 'Garantía estándar para cuadro de bicicleta', 3),
(17, 'Garantía limitada para ruedas', 1),
(18, 'Garantía de pintura contra rayaduras', 1),
(19, 'Garantía estándar para cuadro de bicicleta', 2),
(20, 'Garantía contra corrosión en bicicletas de aluminio', 1),
(21, 'Garantía contra corrosión en bicicletas de aluminio', 3),
(22, 'Garantía estándar para cuadro de bicicleta', 1),
(23, 'Garantía para defectos de fábrica', 2),
(24, 'Garantía contra corrosión en bicicletas de aluminio', 2),
(25, 'Garantía contra corrosión en bicicletas de aluminio', 2),
(26, 'Garantía contra corrosión en bicicletas de aluminio', 2),
(27, 'Garantía estándar para cuadro de bicicleta', 1),
(28, 'Garantía para defectos de fábrica', 1),
(29, 'Garantía contra corrosión en bicicletas de aluminio', 2),
(30, 'Garantía completa en bicicletas eléctricas', 2),
(31, 'Garantía por repuestos originales', 1),
(32, 'Garantía extendida para frenos', 3),
(33, 'Garantía contra corrosión en bicicletas de aluminio', 1),
(34, 'Garantía por repuestos originales', 2),
(35, 'Garantía limitada para accesorios adicionales', 3),
(36, 'Garantía de pintura contra rayaduras', 1),
(37, 'Garantía completa en bicicletas eléctricas', 1),
(38, 'Garantía extendida para suspensión', 1),
(39, 'Garantía de pintura contra rayaduras', 3),
(40, 'Garantía limitada para accesorios adicionales', 2),
(41, 'Garantía estándar para cuadro de bicicleta', 3),
(42, 'Garantía extendida para suspensión', 1),
(43, 'Garantía de pintura contra rayaduras', 2),
(44, 'Garantía de pintura contra rayaduras', 2),
(45, 'Garantía completa en bicicletas eléctricas', 1),
(46, 'Garantía limitada para accesorios adicionales', 1),
(47, 'Garantía por repuestos originales', 3),
(48, 'Garantía estándar para cuadro de bicicleta', 1),
(49, 'Garantía por repuestos originales', 3),
(50, 'Garantía limitada para accesorios adicionales', 2),
(51, 'Garantía extendida para frenos', 2),
(52, 'Garantía para defectos de fábrica', 2),
(53, 'Garantía estándar para cuadro de bicicleta', 1),
(54, 'Garantía para defectos de fábrica', 3),
(55, 'Garantía estándar para cuadro de bicicleta', 2),
(56, 'Garantía por repuestos originales', 3),
(57, 'Garantía por repuestos originales', 1),
(58, 'Garantía limitada para ruedas', 2),
(59, 'Garantía limitada para accesorios adicionales', 3),
(60, 'Garantía limitada para accesorios adicionales', 3),
(61, 'Garantía limitada para accesorios adicionales', 1),
(62, 'Garantía contra corrosión en bicicletas de aluminio', 1),
(63, 'Garantía por repuestos originales', 3),
(64, 'Garantía estándar para cuadro de bicicleta', 2),
(65, 'Garantía de pintura contra rayaduras', 2),
(66, 'Garantía de pintura contra rayaduras', 2),
(67, 'Garantía de pintura contra rayaduras', 3),
(68, 'Garantía completa en bicicletas eléctricas', 1),
(69, 'Garantía completa en bicicletas eléctricas', 1),
(70, 'Garantía extendida para suspensión', 2),
(71, 'Garantía contra corrosión en bicicletas de aluminio', 3),
(72, 'Garantía limitada para accesorios adicionales', 2),
(73, 'Garantía contra corrosión en bicicletas de aluminio', 1),
(74, 'Garantía completa en bicicletas eléctricas', 3),
(75, 'Garantía limitada para accesorios adicionales', 2),
(76, 'Garantía extendida para suspensión', 2),
(77, 'Garantía estándar para cuadro de bicicleta', 1),
(78, 'Garantía limitada para accesorios adicionales', 3),
(79, 'Garantía por repuestos originales', 3),
(80, 'Garantía extendida para frenos', 1),
(81, 'Garantía extendida para suspensión', 3),
(82, 'Garantía limitada para accesorios adicionales', 2),
(83, 'Garantía completa en bicicletas eléctricas', 1),
(84, 'Garantía limitada para accesorios adicionales', 1),
(85, 'Garantía limitada para accesorios adicionales', 3),
(86, 'Garantía por repuestos originales', 2),
(87, 'Garantía limitada para ruedas', 1),
(88, 'Garantía de pintura contra rayaduras', 1),
(89, 'Garantía limitada para ruedas', 2),
(90, 'Garantía extendida para frenos', 1),
(91, 'Garantía extendida para frenos', 3),
(92, 'Garantía completa en bicicletas eléctricas', 3),
(93, 'Garantía estándar para cuadro de bicicleta', 3),
(94, 'Garantía limitada para ruedas', 3),
(95, 'Garantía para defectos de fábrica', 1),
(96, 'Garantía de pintura contra rayaduras', 3),
(97, 'Garantía limitada para accesorios adicionales', 2),
(98, 'Garantía limitada para ruedas', 3),
(99, 'Garantía por repuestos originales', 2),
(100, 'Garantía limitada para ruedas', 3);