INSERT INTO public."Descuento"(
	id_descuento, descuento_porcentual, detalle_descuento)
VALUES
(1, 17, 'Descuento por compra de bicicleta de montaña'),
(2, 4, 'Descuento para estudiantes'),
(3, 14, 'Descuento por bicicletas urbanas'),
(4, 2, 'Descuento por accesorios de seguridad'),
(5, 5, 'Descuento por bicicleta eléctrica'),
(6, 1, 'Descuento por referir a un amigo'),
(7, 9, 'Descuento por bicicleta eléctrica'),
(8, 11, 'Descuento en kits de reparación'),
(9, 10, 'Descuento en compra de luces para bicicleta'),
(10, 14, 'Descuento para estudiantes'),
(11, 17, 'Descuento por compra de bicicleta personalizada'),
(12, 13, 'Descuento para grupos familiares'),
(13, 15, 'Descuento para estudiantes'),
(14, 5, 'Descuento en kits de reparación'),
(15, 11, 'Descuento por accesorios de seguridad'),
(16, 10, 'Descuento por compra en efectivo'),
(17, 12, 'Descuento para grupos familiares'),
(18, 19, 'Descuento por programa de fidelización'),
(19, 2, 'Descuento por paquete de ruedas adicionales'),
(20, 10, 'Descuento para grupos familiares'),
(21, 3, 'Descuento para grupos familiares'),
(22, 1, 'Descuento para estudiantes'),
(23, 5, 'Descuento en compra de soportes para auto'),
(24, 3, 'Descuento por compra de bicicleta de montaña'),
(25, 6, 'Descuento por compra de bicicleta personalizada'),
(26, 19, 'Descuento por compra de bicicleta de montaña'),
(27, 11, 'Descuento para grupos familiares'),
(28, 18, 'Descuento para miembros de clubes deportivos'),
(29, 13, 'Descuento por bicicleta de carretera'),
(30, 6, 'Descuento para grupos familiares'),
(31, 19, 'Descuento en kits de reparación'),
(32, 14, 'Descuento por accesorios de seguridad'),
(33, 7, 'Descuento por paquete de ruedas adicionales'),
(34, 4, 'Descuento en compra de soportes para auto'),
(35, 2, 'Descuento para miembros de clubes deportivos'),
(36, 10, 'Descuento por paquete de ruedas adicionales'),
(37, 2, 'Descuento por referir a un amigo'),
(38, 17, 'Descuento en sistemas de frenos avanzados'),
(39, 6, 'Descuento en casco al comprar bicicleta'),
(40, 8, 'Descuento en compra de soportes para auto'),
(41, 5, 'Descuento por paquete de ruedas adicionales'),
(42, 17, 'Descuento por compra de bicicleta personalizada'),
(43, 11, 'Descuento para estudiantes'),
(44, 14, 'Descuento por bicicleta eléctrica'),
(45, 20, 'Descuento para grupos familiares'),
(46, 8, 'Descuento por promoción de verano'),
(47, 18, 'Descuento por promoción de invierno'),
(48, 11, 'Descuento por bicicletas urbanas'),
(49, 4, 'Descuento por bicicleta de carretera'),
(50, 3, 'Descuento en compra de soportes para auto'),
(51, 3, 'Descuento por bicicleta eléctrica'),
(52, 15, 'Descuento para grupos familiares'),
(53, 20, 'Descuento por paquete de ruedas adicionales'),
(54, 20, 'Descuento por promoción de verano'),
(55, 1, 'Descuento en compra de luces para bicicleta'),
(56, 18, 'Descuento para estudiantes'),
(57, 13, 'Descuento en sistemas de frenos avanzados'),
(58, 5, 'Descuento en compra de luces para bicicleta'),
(59, 8, 'Descuento por programa de fidelización'),
(60, 13, 'Descuento en compra de luces para bicicleta'),
(61, 14, 'Descuento por referir a un amigo'),
(62, 4, 'Descuento por compra en efectivo'),
(63, 6, 'Descuento para estudiantes'),
(64, 6, 'Descuento en sistemas de frenos avanzados'),
(65, 10, 'Descuento por bicicleta de carretera'),
(66, 12, 'Descuento en kits de reparación'),
(67, 7, 'Descuento en compra de soportes para auto'),
(68, 1, 'Descuento para estudiantes'),
(69, 14, 'Descuento por compra de bicicleta de montaña'),
(70, 10, 'Descuento por programa de fidelización'),
(71, 8, 'Descuento en kits de reparación'),
(72, 13, 'Descuento por promoción de verano'),
(73, 11, 'Descuento por promoción de verano'),
(74, 9, 'Descuento por bicicleta eléctrica'),
(75, 19, 'Descuento en sistemas de frenos avanzados'),
(76, 20, 'Descuento en kits de reparación'),
(77, 11, 'Descuento por accesorios de seguridad'),
(78, 15, 'Descuento en sistemas de frenos avanzados'),
(79, 16, 'Descuento por bicicleta eléctrica'),
(80, 16, 'Descuento en casco al comprar bicicleta'),
(81, 12, 'Descuento en casco al comprar bicicleta'),
(82, 17, 'Descuento por promoción de verano'),
(83, 7, 'Descuento por bicicleta eléctrica'),
(84, 18, 'Descuento por bicicleta de carretera'),
(85, 1, 'Descuento por bicicleta eléctrica'),
(86, 20, 'Descuento para grupos familiares'),
(87, 11, 'Descuento por promoción de invierno'),
(88, 12, 'Descuento por bicicleta de carretera'),
(89, 16, 'Descuento por promoción de verano'),
(90, 1, 'Descuento por promoción de verano'),
(91, 17, 'Descuento para grupos familiares'),
(92, 9, 'Descuento por bicicletas urbanas'),
(93, 19, 'Descuento por referir a un amigo'),
(94, 2, 'Descuento en compra de soportes para auto'),
(95, 12, 'Descuento por programa de fidelización'),
(96, 10, 'Descuento por bicicleta eléctrica'),
(97, 5, 'Descuento por bicicleta de carretera'),
(98, 1, 'Descuento por bicicleta de carretera'),
(99, 13, 'Descuento en compra de luces para bicicleta'),
(100, 20, 'Descuento en sistemas de frenos avanzados');